### ISSUE TITLE
I'd love to see "open game" added here!

### ISSUE THREAD

**Issue by JordanTranchina** [KevinBatdorf/steam-raycast#3]
"Search for games" is great, but "open games" would be even better. Thank you for making this!

**Comment by KevinBatdorf** [comment]
You mean to launch a game or open it on Steam? You can do that by searching and pressing `cmd K`


https://user-images.githubusercontent.com/1478421/216232890-ad7c452c-d752-4d6e-b67b-c40126df2043.mov

Or do you mean something else?
